// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhqpfnawwcxuyqjlhiun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocXBmbmF3d2N4dXlxamxoaXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjg4MDEsImV4cCI6MjA2NjYwNDgwMX0.Zo3rhbJzsBoHjRSpbheGPmvLRKbBA6NiLJW5e5TYMFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);